version: 2

models:
  - name: mart_customer_acquisition
    description: "Monthly count of newly acquired customers by province. A customer is considered acquired when they place their first order. Audience: growth and marketing teams."
    columns:
      - name: acquisition_month
        description: "First day of the month in which the customer placed their first order."
      - name: year
        description: "Calendar year of the acquisition month."
      - name: province
        description: "Canadian province of the customer, used to identify regional acquisition patterns."
      - name: new_customers
        description: "Count of distinct customers placing their first ever order in this month and province."

  - name: mart_churn
    description: "Monthly count of customers who have churned by province. A customer is considered churned if they have not placed an order in the last 90 days. Audience: growth and marketing teams."
    columns:
      - name: acquisition_month
        description: "First day of the month in which the customer placed their first order."
      - name: year
        description: "Calendar year of the acquisition month."
      - name: province
        description: "Canadian province of the customer, used to identify regional churn patterns."
      - name: total_customers
        description: "Count of distinct customers who have placed an order in this month and province."
      - name: churned_customers
        description: "Count of distinct customers who have not placed an order in the last 90 days in this month and province."
      - name: churn_rate
        description: "Rate of customers who have not placed an order in the last 90 days in this month and province."
      - name: avg_days_since_last_order
        description: "Average number of days since the last order for customers who have not placed an order in the last 90 days in this month and province."

  - name: mart_customer_ltv
    description: "Average total revenue and customer count by cohort month and cohort year.  Audience: growth and marketing teams."
    columns:
      - name: cohort_month
        description: "Month in which the customer placed their first order."
      - name: year
        description: "Calendar year of the cohort month."
      - name: avg_lifetime_value
        description: "Average total revenue generated by customers in this cohort month and year."
      - name: customer_count
        description: "Count of distinct customers who have placed an order in this cohort month and year."


  - name: mart_discount_effectiveness
    description: "Rate of customers who having used a discount code on their first order, went on to place 2 or more orders, by province, cohort month, and year. A customer is considered to have used a discount code if they have placed their first order with a discount code applied. Audience: growth and marketing teams."
    columns:
      - name: cohort_month
        description: "Month in which the customer placed their first order."
      - name: year
        description: "Calendar year of the cohort month."
      - name: province
        description: "Canadian province of the customer, used to identify regional acquisition patterns."
      - name: discount_repeat_rate
        description: "Rate of customers who having used a discount code on their first order, went on to place 2 or more orders, by province, cohort month, and year."
      - name: non_discount_repeat_rate
        description: "Rate of customers who having not used a discount code on their first order, went on to place 2 or more orders, by province, cohort month, and year."

  - name: mart_repeat_purchase
    description: "Rate of customers who placed 2 or more orders, by province, cohort month, and year. Audience: growth and marketing teams."
    columns:
      - name: cohort_month
        description: "Month in which the customer placed their first order."
      - name: year
        description: "Calendar year of the cohort month."
      - name: province
        description: "Canadian province of the customer, used to identify regional acquisition patterns."
      - name: repeat_customers
        description: "Count of distinct customers who placed 2 or more orders, by province, cohort month, and year."
      - name: total_customers
        description: "Count of distinct customers who placed an order, by province, cohort month, and year."
      - name: repeat_purchase_rate
        description: "Rate of customers who placed 2 or more orders, by province, cohort month, and year."
      - name: avg_days_to_second_order
        description: "Average number of days it took for customers to place their second order, by province, cohort month, and year."